# Generated by Django 6.0 on 2025-12-27 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroBlockchain',
            fields=[
                ('indice', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('empresa_creada', 'Empresa Creada'), ('empresa_modificada', 'Empresa Modificada'), ('producto_creado', 'Producto Creado'), ('producto_modificado', 'Producto Modificado'), ('inventario_actualizado', 'Inventario Actualizado'), ('usuario_creado', 'Usuario Creado')], max_length=50, verbose_name='Tipo de transacción')),
                ('datos', models.JSONField(verbose_name='Datos de la transacción')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Marca de tiempo')),
                ('hash_anterior', models.CharField(blank=True, max_length=64, verbose_name='Hash anterior')),
                ('hash_actual', models.CharField(max_length=64, verbose_name='Hash actual')),
                ('usuario', models.CharField(max_length=100, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Registro Blockchain',
                'verbose_name_plural': 'Registros Blockchain',
                'ordering': ['-indice'],
            },
        ),
    ]
