# Generated by Django 6.0 on 2025-12-27 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroblockchain',
            name='timestamp',
            field=models.DateTimeField(verbose_name='Marca de tiempo'),
        ),
        migrations.AlterField(
            model_name='registroblockchain',
            name='tipo',
            field=models.CharField(choices=[('empresa_creada', 'Empresa Creada'), ('empresa_modificada', 'Empresa Modificada'), ('empresa_eliminada', 'Empresa Eliminada'), ('producto_creado', 'Producto Creado'), ('producto_modificado', 'Producto Modificado'), ('producto_eliminado', 'Producto Eliminado'), ('inventario_actualizado', 'Inventario Actualizado'), ('inventario_eliminado', 'Inventario Eliminado'), ('usuario_creado', 'Usuario Creado'), ('usuario_eliminado', 'Usuario Eliminado')], max_length=50, verbose_name='Tipo de transacción'),
        ),
    ]
